# apiVersion: v1
# kind: Namespace
# metadata:
#   name: genghis-khan

# ---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
  namespace: genghis-khan
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
  namespace: genghis-khan
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: genghis-khan-claim0
  name: genghis-khan-claim0
  namespace: genghis-khan
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: genghis-khan
  name: genghis-khan
  namespace: genghis-khan
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: genghis-khan
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: PAGE_ACCESS_TOKEN
          value: EAADhwucJOOsBAGZCoYnRbPvRG4I6VLJc6nIRe5oAkrzDmXjHNzWwpGpU02zrEmdeci7dSSt3uMTkThlUJKhuI5sxLXfBH3pNtQxPvZC2M0vJZAyZCT9dxn1ZCcp2XDmjz7jOQOZByZABSXHrSFWHoMrxrbaU6ZAO3x99kF1OmfvoQAZDZD
        - name: PORT
          value: "8080"
        - name: REDIS_TYPE
          value: docker
        - name: REDIS_URL
          value: redis:6379
        - name: VERIFY_TOKEN
          value: genghis-khan the power
        image: registry.hub.docker.com/samwang0723/genghis-khan:0.1.3
        imagePullPolicy: Always
        name: genghis-khan
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /go/src
          name: genghis-khan-claim0
        workingDir: /go/src
      restartPolicy: Always
      volumes:
      - name: genghis-khan-claim0
        persistentVolumeClaim:
          claimName: genghis-khan-claim0
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: genghis-khan
  name: genghis-khan
  namespace: genghis-khan
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: genghis-khan
status:
  loadBalancer: {}
