apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: genghis-khan
spec:
  replicas: 1
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: genghis-khan
  resourceVersion: null
spec:
  clusterIP: null
  type: LoadBalancer
  ports:
  - name: "6379"
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: genghis-khan
  namespace: genghis-khan
spec:
  replicas: 2
  serviceName: "genghis-khan"
  selector:
    matchLabels:
      app: genghis-khan
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app: genghis-khan
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: PAGE_ACCESS_TOKEN
          value: EAADhwucJOOsBAGZCoYnRbPvRG4I6VLJc6nIRe5oAkrzDmXjHNzWwpGpU02zrEmdeci7dSSt3uMTkThlUJKhuI5sxLXfBH3pNtQxPvZC2M0vJZAyZCT9dxn1ZCcp2XDmjz7jOQOZByZABSXHrSFWHoMrxrbaU6ZAO3x99kF1OmfvoQAZDZD
        - name: PORT
          value: "8080"
        - name: REDIS_TYPE
          value: docker
        - name: REDIS_URL
          value: redis:6379
        - name: VERIFY_TOKEN
          value: genghis-khan the power
        image: registry.hub.docker.com/samwang0723/genghis-khan:0.1.11
        imagePullPolicy: Always
        name: genghis-khan
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /go/src
          name: genghis-khan-claim0
        workingDir: /go/src
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: genghis-khan-claim0
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: genghis-khan
  namespace: genghis-khan
  resourceVersion: null
spec:
  clusterIP: null
  type: LoadBalancer
  ports:
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: genghis-khan
