apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: drone-deployment
  namespace: genghis-khan
rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: drone-deployment
  namespace: genghis-khan
subjects:
  - kind: ServiceAccount
    name: default
    namespace: genghis-khan
roleRef:
  kind: Role
  name: drone-deployment
  apiGroup: rbac.authorization.k8s.io